### ISSUE TITLE
Bug : After rotating the cube, the command doesn't work properly

### ISSUE THREAD

**Issue by ptechofficial** [vasu-gondaliya/cube#20]
After rotating the cube, if we click on 'left clockwise' button, it still refers to the ring which was left in the initial view.

**Comment by ptechofficial** [comment]
@vasu-gondaliya Can you add the required labels to this issue?

**Comment by vasu-gondaliya** [comment]
Yes, this is a major part remaining in the project. This was in my sight from the very first. All the cube moves are respect to the fixed positions where, White is on top, Green is on Front and Red is on Right Side. All the face turns  are with respect to this configuration. 
Something needs to be added so that for all the 24 configuration, the moves will be consistent.

**Comment by vasu-gondaliya** [comment]
There is always a brute force way available but let's keep it in backup. We can add transition configuration for all the 24 cube configurations for all the 6 moves which will result in array of 24X6 dimension and all the entries need to be done manually.
So if nothing efficient comes up, we can always do this.

**Comment by ptechofficial** [comment]
Yeah, i'll think about this, i might be able to come up with some other way.

**Comment by athanasiab** [comment]
Hello! I would like to work on this issue, is it still open?

**Comment by choia4** [comment]
Hi, is this issue still open?
